### ISSUE TITLE
Bug in English Latest drop down button

### ISSUE THREAD

**Issue by VictoriaAjala** [wagtail/guide#131]
The English latest button does not display the drop down options from the link attached to the guide site.

![Screenshot 2022-10-18 at 13-02-47 wagtail_guide A work-in-progress website to teach Wagtail CMS to content editors moderators and administrators](https://user-images.githubusercontent.com/102407780/196424560-1b46481a-2360-492a-870c-e6749166d2f3.png)

### **Screenshot**
![Screenshot from 2022-10-18 12-14-50](https://user-images.githubusercontent.com/102407780/196414964-9ee432f1-e2ba-46bb-9bb7-b11d6bc9b1b3.png)

**Comment by saevarom** [comment]
This is because at the time you were viewing the site, there were no active translations.
Now we have Icelandic and hopefully more soon, so this menu is populated. 

<img width="329" alt="Screenshot 2022-10-26 at 16 26 05" src="https://user-images.githubusercontent.com/143557/198081768-150785da-1542-4a97-a3bd-e88fea719c0c.png">
