### ISSUE TITLE
Links in a translated page not working

### ISSUE THREAD

**Issue by saevarom** [wagtail/guide#220]
See for example https://guide.wagtail.org/is-latest/how-to/copying-and-aliasing-pages/

I believe I have translated them correctly using the `<a id="a1>` syntax, but they are not working.

**Comment by laymonage** [comment]
Not sure what the issue is, but it seems that the translation went out of sync (probably because the original page in English was modified). I tried re-syncing but for some reason now it says translating "from Icelandic (latest) to Icelandic (latest)". Maybe try deleting the translated page and recreate the translated page? Make sure to save your progress somewhere first though

**Comment by saevarom** [comment]
I deleted the Icelandic version and recreated it, then had to copy all the strings again. It works now.

But as you say, that text "from Icelandic (latest) to Icelandic (latest)" is suspicious and we should perhaps take a closer look if we encounter this again. Closing for now.
