### ISSUE TITLE
Language redirection active even though language not translated

### ISSUE THREAD

**Issue by benebun** [wagtail/guide#253]
Currently when visiting https://guide.wagtail.org/ it redirects to the browser preferred language and shows that language in the dropdown even though that language is not available yet. Which is a bit confusing.
E.g. preferred browser language German redirects to https://guide.wagtail.org/de-latest/ even though the content is not ready yet and displays "Deutsch (latest)" in the language drop down. See screenshot below.

Also, English is not available in the language selection list.

It would be good to disable languages that are not yet translated to avoid confusion I think?

![image](https://user-images.githubusercontent.com/1321740/199749895-ee2f1827-2222-4e5a-90cf-764ed475137c.png)

**Comment by allcaps** [comment]
# Page and page chooser

- The i18n patterns and middleware activate the German locale. See the edit bird, the contents is German.
- In the language chooser, the "Deutsch (latest)" is shown, but the "English (latest)" is removed.
- The content of the page is English homepage. 
- In the edit bird, "Diese Seite bearbeiten" opens the English edit view in the admin.

Conclusion, this is the English homepage with the German locale activated.

# i18n URL pattern + locale middleware

We have all languages in `WAGTAIL_GUIDE_LANGUAGES`, and thus in `LANGUAGES`. Because of that, the translation machinery of i18n_patterns + locale middleware will accept any language as 'valid' and activates the locale.

When I remove the language from `WAGTAIL_GUIDE_LANGUAGES` I get a redirect and 404. Eg:

1. Drop Spanish from `WAGTAIL_GUIDE_LANGUAGES`
2. Open `/es-latest/`
3. Spanish isn't found, redirect kicks in, to `/en-latest/es-latest/`
4. Gives 404.

Note:
- Removing the locales from `LANGUAGES` is not an option, we need them to create Wagtail locales.
- i18n_patterns + locale middleware are pure Django. The don't consider the Wagtail Locale (if it exists) and also not the Wagtail page (if it is live).

# Possible solution

Create a middleware to check for a published homepage for the given locale. 
See: https://github.com/wagtail/guide/pull/257

# Fix upstream?

I have yet to investigate, but I think this would happen in any Wagtail multilingual site where there are more language codes in `LANGUAGES` then there are published homepages.
