### ISSUE TITLE
Trial Vale for style guide linting

### ISSUE THREAD

**Issue by activus-d** [wagtail/guide#286]

**Comment by activus-d** [comment]
# What is Vale?
vale is a prose linting command-line tool. It is used to ensure that written work adheres to a particular style.

## How Vale can help with Wagtail user guide documentation
Vale will help ensure that the Wagtail user guide documentation remains consistent in its grammar and writing style.

## What are the different ways Vale can be integrated into Wagtail?
vale can be installed directly as a package in the Wagtail source code docs directory to check for inconsistency.

For the Wagtail user guide documentation project, which uses Wagtail CMS, the draft of the content can be in markdown format. This is followed by installing Vale directly in the file's directory. The draft can then be transferred to the Guide using Wagtail's admin interface.


```Note
Final decision: My drafts will be in markdown format and I'll use Vale to check for inconsistencies and make corrections before adding the content to the user guide via the Wagtail admin interface.
```

**Comment by thibaudcolas** [comment]
I’ll close this now because I believe the trial is complete. Vale seems to work quite well!

One thing I’d like us to revisit is using Markdown for your drafts – it helps with Vale, but complicates reviews, and I’m uncertain whether it works well enough for images (screenshots are a critical part of the guide).

I’ll create a separate task for us to discuss this, and if we keep Markdown, find a content authoring workflow that simplifies reviews.
