### ISSUE TITLE
home page slug is included in search results

### ISSUE THREAD

**Issue by Hitansh-Shah** [wagtail/guide#50]
According to my understanding, the root page can have a slug but still it will be available on `/`. The `buildfixtures` command creates a home page with slug `home-x`. However that slug in not reflected in url of any of the pages. Therefore tutorial will be available on `/tutorial/` rather than `/home-x/tutorial/`. However in search results every url includes the slug and hence on clicking those url results in 404. For eg: `/home-x/tutorial/` will be returned if we searched for tutorial and clicking on it will give 404 not found.

Currently I have handled this by removing every instance of `home-x` from the search results that are returned.
`resultLink.href = result.url_path.replace('home-x/', '').replace('home-x-', '')`

I don't know what is the best way to handle or avoid this. Maybe check if there exists a slug in home page and if yes then remove it?

**Comment by Hitansh-Shah** [comment]
@allcaps @vossisboss .

**Comment by thibaudcolas** [comment]
The problem is that we’re using pages’ `url_path` field to generate the links, which isn’t meant to be used like this (as it does contain the site root’s slug, which is rarely useful).

Have a look at how Wagtail’s built-in page serializer does this, using the [`full_url`](https://docs.wagtail.org/en/stable/reference/pages/model_reference.html#wagtail.models.Page.full_url) attribute instead: https://github.com/wagtail/wagtail/blob/849d4d71cae41de56e43832546429cbb8ad289d5/wagtail/api/v2/serializers.py#L371

We will need to update which field is used in [our serializer](https://github.com/wagtail/guide/blob/f1b33eb1be8e96a99ac89e5200da609cea54baf7/apps/search/views.py#L48), as well as change the JS code to use the different field name.

**Comment by Hitansh-Shah** [comment]
Thanks @thibaudcolas . I have opened a PR for this.
