### ISSUE TITLE
Define permission groups / content review workflow

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/guide#73]
This covers both:

- Our methodology to keep content up-to-date
- The permissions modelling & setup in Wagtail, CMS and code

**Comment by allcaps** [comment]
Some stuff I did to set up German:

1. Create the German locale https://guide.wagtail.org/admin/locales/
2. Copy for translation of the complete English-latest page tree to German (not sure if I'd do that, or leave it to the editors?) 
3. Create a collection for "German latest"
4. Create an Editor group "German", no latest. I assume that members of this group could 'submit for approval on any German page? No matter the Wagtail version? Permissions:
  - Access Wagtail admin
  - Add and edit for the German homepage (and all descendants)
  - Image permissions on the German latest collection, add, edit, choose
6. Create the users and add them to the German group

Ask the users to reset their passwords via https://guide.wagtail.org/admin/password_reset/


Some food for thought:
- Should we nest collections? Eg `German -> latest` and `German -> 4.0`
- Can we not manage passwords in the admin? Seems better to leave this completely at the new users side.
- Should we automatically create, draft homepages, collections and permission groups for all languages? To ease te process?
- When will we publish a translation? When it is 100% complete?
- Seems we need 'language leaders' with publish permissions.

**Comment by saevarom** [comment]
Some notes from me on some of those points:

What I found out when testing out the translation process was that the user belonging to the Icelandic group did not have permissions to submit pages for moderation. I could not figure out what was missing to enable that. It's so much easier to just review submitted pages than going through the translations report, especially since there is a bug in that report which marks pages an incomplete when they are not.

Regarding user invites, then that has been something I've wanted to have in Wagtail for a long time now. There is an open issue for it, but no real milestone or backing behind it. I think this should be a core feature of Wagtail: https://github.com/wagtail/wagtail/issues/1577

I think creating all the homepages as drafts for all languages would clutter the site very much, since, let's be honest, many of them will probably never be translated...

I agree on the langague leaders, they should have publish permissions. If not, then someone with administrator access will have verify that translation is done and publish the language.

**Comment by thibaudcolas** [comment]
On user invites – could it be as simple as randomly generating passwords to create accounts, and then sending a different "set your password" email and different "set your password" page, so from the user’s perspective it’s as if they accepted an invitation rather than reset their password?

Collections nesting: right now they’re nested with versions at the top level. I’ve assumed it’d be more likely to do bulk actions for things based on their version than based on the language, and I have a feeling the site would be easier to manage if we assumed any non-latest translation was largely set in stone, save for admin-level tweaks.
